### ISSUE TITLE
[BUG] An error has encountered while trying to load this plugin v2.2.9

### ISSUE THREAD

**Issue by chanhh01** [notmike101/betterdiscord-google-fonts#60]
BetterDiscord ran into a problem this morning for me, and after repairing better discord, google font plugin failed

**Comment by chanhh01** [comment]
`Error: ENOENT: no such file or directory, lstat 'C:\Users\User\AppData\Local\Discord\app-1.0.9006\betterdiscord'
    at Object.j [as realpathSync] (<anonymous>:4:331996)
    at Function.getFilePath (<anonymous>:4:333266)
    at Function._load (<anonymous>:4:333361)
    at <anonymous>:4:336552
    at eval (betterdiscord://plugins/betterdiscord-google-fonts.plugin.js:92:20)
    at Object.requireAddon (<anonymous>:4:39739)
    at Object.loadAddon (<anonymous>:4:9809)
    at Object.loadAddon (<anonymous>:4:37466)
    at AsyncFunction.<anonymous> (<anonymous>:4:7801)`

**Comment by chanhh01** [comment]
![image](https://user-images.githubusercontent.com/84566394/195234185-e4b6dfce-7bb0-43d1-8a61-47a733ce0d04.png)

**Comment by RevanAnders** [comment]
Replicated, bug confirmed.

**Comment by notmike101** [comment]
@chanhh01 @Roszek-Dragon Can either of you send me the version of Discord and BetterDiscord that you're using?

**Comment by ashergz** [comment]
Discord version: Stable 151983 (3f2a993) Host 1.0.9006
BD 1.8.0

Btw, discord recently made some changes on their end which rendered pretty much all the plugins unusable. Yours somehow was still working up until this morning.

**Comment by Inui-senpai** [comment]
By the way, the folder listed in error log really doesn't exist anymore after repairing BetterDiscord:
![Snap1720](https://user-images.githubusercontent.com/29918546/195536693-f5abf27f-b7bb-4b85-bd41-e5891db27dee.png)

**Comment by chanhh01** [comment]
@notmike101 my discord version is 1.0.9006

**Comment by ashergz** [comment]
In the meantime, I'm using this css snippet to use the font of my choice:

> /*  To add a font, either install the font on your computer through the TTF file, or @import a font from http://fonts.google.com/ */
> 
> :root {
> --font: 'Comic Sans MS';
>}
>
>::placeholder, body, button, input, select, textarea {
    font-family: var(--font), sans-serif;
}

**Comment by Inui-senpai** [comment]
> In the meantime, I'm using this css snippet to use the font of my choice:

It works, but doesn't cover all fonts that can be replaced. So I took code from the #36 and slightly modified it, and it works like a charm.

**Comment by chanhh01** [comment]
> > In the meantime, I'm using this css snippet to use the font of my choice:
> 
> It works, but doesn't cover all fonts that can be replaced. So I took code from the #36 and slightly modified it, and it works like a charm.

may i know how u do it? is there something that im doing wrong?
![image](https://user-images.githubusercontent.com/84566394/196318777-437c83e6-9d4b-461c-a42b-d1c44690fc1e.png)

**Comment by Inui-senpai** [comment]
> may i know how u do it? is there something that im doing wrong?

Open User Settings - Custom CSS, copypaste this code (and replace "Whitney" with your font name, if it's already installed in your OS):
```css
:root {
    --font-primary: "Whitney" !important;
    --font-display: "Whitney" !important;
    --font-headline: "Whitney" !important;
}
```
Then press Update and Save.

**Comment by KKITAANIK** [comment]
This remains an issue; I have the following traceback:
```
Error: ENOENT: no such file or directory, lstat 'C:\Users\pu0aw\AppData\Local\Discord\app-1.0.9013\betterdiscord'
    at Object.T [as realpathSync] (betterdiscord/renderer.js:4:327228)
    at L.getFilePath (betterdiscord/renderer.js:4:328498)
    at L._load (betterdiscord/renderer.js:4:328593)
    at betterdiscord/renderer.js:4:331784
    at eval (betterdiscord://plugins/betterdiscord-google-fonts.plugin.js:92:20)
    at M.requireAddon (betterdiscord/renderer.js:4:35818)
    at M.loadAddon (betterdiscord/renderer.js:4:8323)
    at M.loadAddon (betterdiscord/renderer.js:4:33490)
    at AsyncFunction.<anonymous> (betterdiscord/renderer.js:4:6315)
```
I'm on Better Discord v1.9.3
